# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install
      run: npm ci
      working-directory: covidstats
    - name: build it
      run: npm run build --if-present
      working-directory: covidstats
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.1
      with:
        name: files
        # A file, directory or wildcard pattern that describes what to upload
        path: 
          covidstats/build
          covidstats/package.json
          covidstats/firebase.json
          covidstats/.firebaserc
        retention-days: 2
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: files
          path: 
            covidstats/build
            covidstats/package.json
            covidstats/firebase.json
            covidstats/.firebaserc 
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
